config/routes.rb
Rails.application.routes.draw do

  resources :recipes do
    resources :procedures, :only => :show
  end

  resources :procedures, :except => :show
  resources :foods
  resources :values

  root 'recipes#index'

  post 'values/new'
  post 'procedures/new'
  post 'recipes/new'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_attached_file :image,
                    :styles => {
                      :thumb => "160x200",
                      :image => "350x400"
                    }

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
 
  has_many :procedures, :dependent => :destroy
  has_many :values, :dependent => :destroy

  class << self
    def search(search)
      logger.debug("search")
      if search
        logger.debug("search #{search}")
        Recipe.where(['name LIKE ?', "%#{search}%"])
      else
        logger.debug("search all")
        Recipe.all
      end
    end
  end


end

app/controllers/recipes_controller.rb
# coding:utf-8
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.search(params[:search])
  end

  def show
    @recipe = Recipe.find(params[:id])
    @procedures = Procedure.where(recipe_id: params[:id])
  end

  def new
    @recipe = Recipe.new
    @values = params[:value]
    @procedures = params[:procedure]

    if @procedures.blank?
      flash[:error] = "手順を入力してください"
      redirect_to :controller=>"procedures", :action=>"new", :procedure => params[:procedure], :value => params[:value], :food_id => params[:food_id], :from_value=>true
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      # do nothing
    else
      logger.debug("recipe save failed!")
    end

    params[:procedure].each { |p| 
      @procedure = Procedure.new
      @procedure.play = p[:play]
      @procedure.number = p[:number]
      @procedure.detail = p[:detail]
      @procedure.sec = p[:sec]
      @procedure.recipe = @recipe
      logger.debug(@procedure.inspect)
      if @procedure.save
        # do nothing
      else
        logger.debug("recipe save failed!")
      end
    }

    params[:value].each { |v| 
      @value = Value.new
      @value.value = v[:value]
      @value.food_id = v[:food_id]
      @value.recipe = @recipe
      logger.debug(@procedure.inspect)
      if @value.save
        # do nothing
      else
        logger.debug("value save failed!")
      end
    }

    @procedures = @recipe.procedures
    @values = @recipe.values
    logger.debug(@procedures.inspect)
    logger.debug(@values.inspect)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.xml  { head :ok }
    end
  end

  private
    def recipe_params
      params[:recipe].permit(
        :name,
        :image
        )
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <% if @recipe.image.present? then %>
        <%= image_tag @recipe.image.url(:image) %>
      <% else %>
        <%= image_tag "noimage.jpg", :width=>350 %>
      <% end %>
    </div>
    <div class="col-md-4">
      <h2 style="margin-top:0px"><strong>作り方</strong></h2>
      <div class="procedure-list">
        <dl>
          <% @procedures.each do |procedure| %>
            <div class="procedure-entry">
              <dt>手順<%= procedure.number %></dt>
              <dd>
              <%= procedure.detail %>
              <% if procedure.play%>
                （<%= procedure.min_text %>分<%= procedure.sec_text %>秒）
              <% end %>
              </dd>
            </div>
          <% end %>
        </dl>
      </div>
    </div>
  </div><!-- .row -->
</div><!-- .container --> 

app/views/recipes/create.html.erb
<div class="title">
  <h1><strong>レシピを登録しました</strong></h1>
</div>

<h4>ー新しいレシピ：<a href="/recipes/<%= @recipe.id %>"><%= @recipe.name %></a></h4>

<%= render 'show' %>

<div class="next-btn">
  <%= link_to root_path do %>
    <p><button type="button" class="btn btn-primary">TOPに戻る</button></p>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class="title">
  <h1><strong>タイタニック角煮（仮）</strong><small>＜レシピを検索＞</small></h1>
</div>

<%= form_tag recipes_path, :method => 'get' do %>
  <div class="form-search">
    <%= text_field_tag :search, params[:search], :size=>50 %>
    <button type="search" class="btn btn-primary btn-search">検索</button>
  </div>
<% end %>

<div class="recipe-thumbnails">
  <ul class="thumbnails">
    <% @recipes.each do |recipe| %>
      <div class="thumbnail-block">
        <%= link_to recipe_path(recipe) do %>
          <div class="thumbnail">
            <% if recipe.image.present? then %>
              <%= image_tag recipe.image.url(:thumb) %>
            <% else %>
              <%= image_tag "noimage.jpg" %>
            <% end %>
            <div class="caption">
              <strong><%= recipe.name %></strong>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<div class="title">
  <h1><strong>写真・タイトルの登録</strong><small>＜写真を選択してタイトルを入力＞</small></h1>
</div>
<%= form_for(@recipe, :url=>{:action=>'create'}, :class=>"form-horizontal") do |f| %>

  <div class="backbrown">
    <table class="table">
      <tr align="center" class="column-margin"><td><%= f.file_field :image %></td></tr>
      <tr align="center" class="column-margin"><td>レシピ名:<%= f.text_field :name %></td></tr>
    </table>

    <% @procedures.each do |procedure| %>
      <% if procedure[:sec].to_i != 0 %>
        <%= hidden_field_tag "procedure[][play]", true %>
      <% else %>
        <%= hidden_field_tag "procedure[][play]", false %>
      <% end %>
      <%= hidden_field_tag "procedure[][number]", procedure[:number] %>
      <%= hidden_field_tag "procedure[][detail]", procedure[:detail] %>
      <%= hidden_field_tag "procedure[][sec]", procedure[:sec] %>
    <% end %>
    <% @values.each do |value| %>
      <%= hidden_field_tag "value[][value]", value[:value] %>
      <%= hidden_field_tag "value[][food_id]", value[:food_id] %>
    <% end %>
  </div><!-- backbrown -->

  <div class="next-btn">
    <p><button type="submit" class="btn btn-primary">レシピを登録</button></p>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div class="title">
  <h1><strong><%= @recipe.name %></strong><small>のレシピ</small>
    <div class="next-btn">
      <%= link_to recipe_path(@recipe), method: 'DELETE' do %>
        <p><button type="button" class="btn btn-danger">削除</button></p>
      <% end %>
    </div>
  </h1>
</div>


<%= render 'show' %>

<div class="coock-start">
  <%= form_tag recipe_procedure_path(@recipe.id, @recipe.procedures.first.id),:method=>:get do %>
    動画のキーワード：<%= text_field_tag :key, "", :size=>50 %>
    <button type="submit" class="btn btn-primary">スタート</button>
  <% end %>
</div>