config/routes.rb
Rails.application.routes.draw do

  resources :recipes do
    resources :procedures, :only => :show
  end

  resources :procedures, :except => :show
  resources :foods
  resources :values

  root 'recipes#index'

  post 'values/new'
  post 'procedures/new'
  post 'recipes/new'

end

app/models/food.rb
class Food < ActiveRecord::Base
	has_many :values
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def index
		@foods = Food.all
	end

	def new
		@foods = Food.all
		@categories = [FD_CATEGORY_MEAT, FD_CATEGORY_FISH, FD_CATEGORY_VEGE, FD_CATEGORY_EGG, FD_CATEGORY_RETORT, FD_CATEGORY_SPICE, FD_CATEGORY_FURUIT]
		@cat_name = [FD_NAME_MEAT, FD_NAME_FISH, FD_NAME_VEGE, FD_NAME_EGG, FD_NAME_RETORT, FD_NAME_SPICE, FD_NAME_FURUIT]
		@sub_categories = [FD_SUBCATEGORY_BEEF, FD_SUBCATEGORY_PORK, FD_SUBCATEGORY_CHICKEN, FD_SUBCATEGORY_FISH, FD_SUBCATEGORY_VEGE, FD_SUBCATEGORY_RICE, FD_SUBCATEGORY_NOODLE, FD_SUBCATEGORY_EGG, FD_SUBCATEGORY_POWDER, FD_SUBCATEGORY_PROCESS_MEAT, FD_SUBCATEGORY_PROCESS_VEGE, FD_SUBCATEGORY_PROCESS_FISH, FD_SUBCATEGORY_DRY, FD_SUBCATEGORY_PICKLE, FD_SUBCATEGORY_BOTTLE , FD_SUBCATEGORY_RETORT, FD_SUBCATEGORY_CONDIMENT, FD_SUBCATEGORY_DRINK, FD_SUBCATEGORY_SAUCE, FD_SUBCATEGORY_SPICE, FD_SUBCATEGORY_FRUIT]
		@sub_name = [FD_SUBNAME_BEEF, FD_SUBNAME_PORK, FD_SUBNAME_CHICKEN, FD_SUBNAME_FISH, FD_SUBNAME_VEGE, FD_SUBNAME_RICE, FD_SUBNAME_NOODLE, FD_SUBNAME_EGG, FD_SUBNAME_POWDER, FD_SUBNAME_PROCESS_MEAT, FD_SUBNAME_PROCESS_VEGE, FD_SUBNAME_PROCESS_FISH, FD_SUBNAME_DRY, FD_SUBNAME_PICKLE, FD_SUBNAME_BOTTLE , FD_SUBNAME_RETORT, FD_SUBNAME_CONDIMENT, FD_SUBNAME_DRINK, FD_SUBNAME_SAUCE, FD_SUBNAME_SPICE, FD_SUBNAME_FRUIT]
	end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<h1>食材</h1>

<ul>

  <% @foods.each do |food| %>
  	<%= check_box_tag "select[]", food[:id] %>
  	<%= food[:name] %>
  	(<%= food[:category]%>) <br>
  <% end %>
<br>
  <%= link_to "next", new_value_path() %>
</ul>

app/views/foods/new.html.erb
<div class="title">
  <h1><strong>食材の登録</strong><small>＜使う食材の選択＞</small></h1>
</div>

<%= form_tag('/values/new') do %>

  <ul class="nav nav-tabs">
    <% @categories.each do |category| %>
      <% if category == FD_CATEGORY_MEAT %>
        <li class="active">
      <% else %>
        <li>
      <% end %>

      <% str = "#tab"+category.to_s %>
      <a href=<%= str %> data-toggle="tab"><%= @cat_name[category - 1] %></a>
      </li>
    <% end %>
  </ul>

  <div id="myTabContent" class="tab-content">
    <% count = 0 %>
    <% @categories.each do |category| %>
      <% str = "tab" + category.to_s %>
      <% if category == FD_CATEGORY_MEAT %>
        <div class="tab-pane fade in active" id=<%= str %> >
      <% else %>
        <div class="tab-pane fade" id=<%= str %> >
      <% end %>
        <% @foods.each do |food| %>
          <% if food[:category] == category %>
            <% if food[:id] == @sub_categories[count] %>
              <% str = "▼"+@sub_name[count].to_s %>
              <div class="sub-category"><%= str %></div>
              <% count += 1 %>
            <% end %>
            <div class="checklist">
              <%= check_box_tag "select[]", food[:id], checked=false, :id=>"food_#{food[:id]}" %>
              <label for="food_<%= food[:id] %>"><%= food[:name] %></label>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div><!-- .tab-content -->

  <div class="next-btn">
    <p><button type="submit" class="btn btn-primary">次へ</button></p>
  </div>
<% end %>